import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialPhase1Schema1790611681854 implements MigrationInterface {
    name = 'InitialPhase1Schema1790611681854'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "workflow_actions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "business_id" uuid NOT NULL, "status" smallint NOT NULL DEFAULT '1', "created_by_id" uuid NOT NULL, "created_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by_id" uuid NOT NULL, "updated_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_on" TIMESTAMP WITH TIME ZONE, "workflow_id" uuid NOT NULL, "action_type" character varying(100) NOT NULL, "config" jsonb NOT NULL DEFAULT '{}', CONSTRAINT "PK_94d8dabade2a0ee1185e2753272" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6a66686198f5bf0a4e0a339102" ON "workflow_actions" ("business_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4263dbc50a0e2a450a0244e422" ON "workflow_actions" ("workflow_id") `);
        await queryRunner.query(`CREATE TABLE "webhook_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "business_id" uuid NOT NULL, "status" smallint NOT NULL DEFAULT '1', "created_by_id" uuid NOT NULL, "created_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by_id" uuid NOT NULL, "updated_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_on" TIMESTAMP WITH TIME ZONE, "event_type" character varying(100) NOT NULL, "payload" jsonb NOT NULL, "delivery_status" character varying(50) NOT NULL DEFAULT 'pending', "delivery_attempts" smallint NOT NULL DEFAULT '0', "response_summary" character varying(500), CONSTRAINT "PK_4cba37e6a0acb5e1fc49c34ebfd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_42f64325175fde14bc96827cfd" ON "webhook_events" ("business_id") `);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(255) NOT NULL, "password_hash" character varying(255) NOT NULL, "first_name" character varying(120), "last_name" character varying(120), "avatar_url" character varying(500), "status" smallint NOT NULL DEFAULT '1', "created_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_on" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TABLE "workspaces" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "business_id" uuid NOT NULL, "status" smallint NOT NULL DEFAULT '1', "created_by_id" uuid NOT NULL, "created_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by_id" uuid NOT NULL, "updated_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_on" TIMESTAMP WITH TIME ZONE, "name" character varying(255) NOT NULL, "slug" character varying(120) NOT NULL, "organization_id" uuid NOT NULL, "settings" jsonb, CONSTRAINT "PK_098656ae401f3e1a4586f47fd8e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8e4db55375ad62da39bf574bea" ON "workspaces" ("business_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b8e9fe62e93d60089dfc4f175f" ON "workspaces" ("slug") `);
        await queryRunner.query(`CREATE TABLE "workspace_members" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "business_id" uuid NOT NULL, "status" smallint NOT NULL DEFAULT '1', "created_by_id" uuid NOT NULL, "created_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by_id" uuid NOT NULL, "updated_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_on" TIMESTAMP WITH TIME ZONE, "user_id" uuid NOT NULL, "role" character varying(50) NOT NULL DEFAULT 'member', CONSTRAINT "PK_22ab43ac5865cd62769121d2bc4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ba00250f3b86a102d1653c5cda" ON "workspace_members" ("business_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4e83431119fa585fc7aa8b817d" ON "workspace_members" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "webhook_receivers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "business_id" uuid NOT NULL, "status" smallint NOT NULL DEFAULT '1', "created_by_id" uuid NOT NULL, "created_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by_id" uuid NOT NULL, "updated_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_on" TIMESTAMP WITH TIME ZONE, "name" character varying(255) NOT NULL, "target_url" character varying(1000) NOT NULL, "secret_key" character varying(255), "subscribed_events" jsonb NOT NULL DEFAULT '[]', CONSTRAINT "PK_e4308df12b10fa246d1d618f66b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e2c8160233cf87b86c30c7ebe5" ON "webhook_receivers" ("business_id") `);
        await queryRunner.query(`CREATE TABLE "workflow_triggers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "business_id" uuid NOT NULL, "status" smallint NOT NULL DEFAULT '1', "created_by_id" uuid NOT NULL, "created_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by_id" uuid NOT NULL, "updated_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_on" TIMESTAMP WITH TIME ZONE, "workflow_id" uuid NOT NULL, "trigger_type" character varying(100) NOT NULL, "config" jsonb NOT NULL DEFAULT '{}', CONSTRAINT "PK_80db6a92ba8ada13f99dd8e8839" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cf6f52f2556330ac10b52a3e3f" ON "workflow_triggers" ("business_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a69d4dba42b12bffafa4be9804" ON "workflow_triggers" ("workflow_id") `);
        await queryRunner.query(`CREATE TABLE "workflow_definitions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "business_id" uuid NOT NULL, "status" smallint NOT NULL DEFAULT '1', "created_by_id" uuid NOT NULL, "created_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by_id" uuid NOT NULL, "updated_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_on" TIMESTAMP WITH TIME ZONE, "name" character varying(255) NOT NULL, "description" text, "is_active" boolean NOT NULL DEFAULT true, "definition" jsonb NOT NULL DEFAULT '{}', CONSTRAINT "PK_4f92fadfc5fb722f080ceaec272" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0295721f97f1658e87f335626c" ON "workflow_definitions" ("business_id") `);
        await queryRunner.query(`CREATE TABLE "global_configs" ("key" character varying(100) NOT NULL, "value" jsonb NOT NULL, "description" character varying(255), "updated_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_de954a917c3d76ababc6dcca9e5" PRIMARY KEY ("key"))`);
        await queryRunner.query(`CREATE TABLE "workflow_executions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "business_id" uuid NOT NULL, "status" smallint NOT NULL DEFAULT '1', "created_by_id" uuid NOT NULL, "created_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by_id" uuid NOT NULL, "updated_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_on" TIMESTAMP WITH TIME ZONE, "workflow_id" uuid NOT NULL, "trigger_event" character varying(100) NOT NULL, "execution_status" character varying(50) NOT NULL DEFAULT 'running', "execution_log" jsonb, CONSTRAINT "PK_9d49b5c86c267d902145ed42c9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e6222f046b4fad2cab8116845e" ON "workflow_executions" ("business_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6347f114eeaac28722f959f6e3" ON "workflow_executions" ("workflow_id") `);
        await queryRunner.query(`CREATE TABLE "organizations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "slug" character varying(120) NOT NULL, "status" smallint NOT NULL DEFAULT '1', "created_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_on" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_6b031fcd0863e3f6b44230163f9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_963693341bd612aa01ddf3a4b6" ON "organizations" ("slug") `);
        await queryRunner.query(`CREATE TABLE "messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "business_id" uuid NOT NULL, "status" smallint NOT NULL DEFAULT '1', "created_by_id" uuid NOT NULL, "created_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by_id" uuid NOT NULL, "updated_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_on" TIMESTAMP WITH TIME ZONE, "conversation_id" uuid NOT NULL, "sender_type" character varying(50) NOT NULL, "content" text NOT NULL, "message_type" character varying(50) NOT NULL DEFAULT 'text', "metadata" jsonb, CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1fe66d9cd8e2d40ddd8994d703" ON "messages" ("business_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3bc55a7c3f9ed54b520bb5cfe2" ON "messages" ("conversation_id") `);
        await queryRunner.query(`CREATE TABLE "segments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "business_id" uuid NOT NULL, "status" smallint NOT NULL DEFAULT '1', "created_by_id" uuid NOT NULL, "created_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by_id" uuid NOT NULL, "updated_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_on" TIMESTAMP WITH TIME ZONE, "name" character varying(255) NOT NULL, "filter_criteria" jsonb NOT NULL, CONSTRAINT "PK_beff1eec19679fe8ad4f291f04e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9c89697164c20b0b9711fa03f5" ON "segments" ("business_id") `);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspace_id" uuid NOT NULL, "actor_id" uuid NOT NULL, "action" character varying(120) NOT NULL, "entity_name" character varying(120) NOT NULL, "entity_id" uuid, "metadata" jsonb, "created_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e140f8ddef870ea93925f251f2" ON "audit_logs" ("workspace_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_177183f29f438c488b5e8510cd" ON "audit_logs" ("actor_id") `);
        await queryRunner.query(`CREATE TABLE "participants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "business_id" uuid NOT NULL, "status" smallint NOT NULL DEFAULT '1', "created_by_id" uuid NOT NULL, "created_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by_id" uuid NOT NULL, "updated_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_on" TIMESTAMP WITH TIME ZONE, "conversation_id" uuid NOT NULL, "user_id" uuid NOT NULL, "role" character varying(50) NOT NULL DEFAULT 'assigned_agent', CONSTRAINT "PK_1cda06c31eec1c95b3365a0283f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_407e4e86642d493b6d9ca7b45a" ON "participants" ("business_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_de8978490834e2e9cb3c3fc806" ON "participants" ("conversation_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1427a77e06023c250ed3794a1b" ON "participants" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "conversations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "business_id" uuid NOT NULL, "status" smallint NOT NULL DEFAULT '1', "created_by_id" uuid NOT NULL, "created_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by_id" uuid NOT NULL, "updated_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_on" TIMESTAMP WITH TIME ZONE, "channel_id" uuid NOT NULL, "contact_id" uuid NOT NULL, "last_message_at" TIMESTAMP WITH TIME ZONE, "unread_count" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_ee34f4f7ced4ec8681f26bf04ef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d2ec6f5e4d9d16443e841ed4d8" ON "conversations" ("business_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1a99838ee2e2e940ad98ed2e9d" ON "conversations" ("channel_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3e605129623b629ddd0583740d" ON "conversations" ("contact_id") `);
        await queryRunner.query(`CREATE TABLE "contacts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "business_id" uuid NOT NULL, "status" smallint NOT NULL DEFAULT '1', "created_by_id" uuid NOT NULL, "created_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by_id" uuid NOT NULL, "updated_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_on" TIMESTAMP WITH TIME ZONE, "first_name" character varying(120), "last_name" character varying(120), "phone_number" character varying(50), "instagram_handle" character varying(120), "email" character varying(255), "custom_attributes" jsonb NOT NULL DEFAULT '{}', "tags" jsonb NOT NULL DEFAULT '[]', CONSTRAINT "PK_b99cd40cfd66a99f1571f4f72e6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_569eb5246771327e8e41fda5ce" ON "contacts" ("business_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_736eb30c4220859bd55d8e7953" ON "contacts" ("phone_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_d465e2a1ae2f8d311e9b09f39f" ON "contacts" ("instagram_handle") `);
        await queryRunner.query(`CREATE TABLE "audiences" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "business_id" uuid NOT NULL, "status" smallint NOT NULL DEFAULT '1', "created_by_id" uuid NOT NULL, "created_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by_id" uuid NOT NULL, "updated_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_on" TIMESTAMP WITH TIME ZONE, "name" character varying(255) NOT NULL, "description" text, "contact_count" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_d87c8fe1be471372dd505a9dc1f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ad7a73cff3ca8bd780ee0a9f81" ON "audiences" ("business_id") `);
        await queryRunner.query(`CREATE TABLE "campaigns" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "business_id" uuid NOT NULL, "status" smallint NOT NULL DEFAULT '1', "created_by_id" uuid NOT NULL, "created_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by_id" uuid NOT NULL, "updated_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_on" TIMESTAMP WITH TIME ZONE, "name" character varying(255) NOT NULL, "channel_type" character varying(50) NOT NULL, "template_id" uuid, "scheduled_at" TIMESTAMP WITH TIME ZONE, "total_recipients" integer NOT NULL DEFAULT '0', "sent_count" integer NOT NULL DEFAULT '0', "delivered_count" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_831e3fcd4fc45b4e4c3f57a9ee4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_778013f0785179c0d7ea5c279e" ON "campaigns" ("business_id") `);
        await queryRunner.query(`CREATE TABLE "channels" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "business_id" uuid NOT NULL, "status" smallint NOT NULL DEFAULT '1', "created_by_id" uuid NOT NULL, "created_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by_id" uuid NOT NULL, "updated_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_on" TIMESTAMP WITH TIME ZONE, "type" character varying(50) NOT NULL, "name" character varying(255) NOT NULL, "channel_identifier" character varying(255) NOT NULL, "credentials" jsonb, "is_connected" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_bc603823f3f741359c2339389f9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_466129a2c4eab22f4bb5109de1" ON "channels" ("business_id") `);
        await queryRunner.query(`CREATE TABLE "templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "business_id" uuid NOT NULL, "status" smallint NOT NULL DEFAULT '1', "created_by_id" uuid NOT NULL, "created_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by_id" uuid NOT NULL, "updated_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_on" TIMESTAMP WITH TIME ZONE, "name" character varying(255) NOT NULL, "category" character varying(50) NOT NULL DEFAULT 'utility', "content" text NOT NULL, "variables" jsonb NOT NULL DEFAULT '[]', CONSTRAINT "PK_515948649ce0bbbe391de702ae5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_719d46d8ea30d09f6c62978023" ON "templates" ("business_id") `);
        await queryRunner.query(`CREATE TABLE "campaign_recipients" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "business_id" uuid NOT NULL, "status" smallint NOT NULL DEFAULT '1', "created_by_id" uuid NOT NULL, "created_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by_id" uuid NOT NULL, "updated_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_on" TIMESTAMP WITH TIME ZONE, "campaign_id" uuid NOT NULL, "contact_id" uuid NOT NULL, "delivery_status" character varying(50) NOT NULL DEFAULT 'pending', "sent_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_30d346f6af084aa7b916945a4f1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_68e2c25aa52093d28af9bd2011" ON "campaign_recipients" ("business_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_37f67f778844dcc3a0d641a617" ON "campaign_recipients" ("campaign_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_fa75aa29a9c3f1c980cde5dbf8" ON "campaign_recipients" ("contact_id") `);
        await queryRunner.query(`CREATE TABLE "businesses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "name" character varying(255) NOT NULL, "slug" character varying(120) NOT NULL, "category" character varying(100) NOT NULL DEFAULT 'General', "logo_url" character varying(500), "phone" character varying(50), "website" character varying(255), "location" character varying(255), "status" smallint NOT NULL DEFAULT '1', "settings" jsonb, "created_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_on" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_bc1bf63498dd2368ce3dc8686e8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cbb98c2d1e4c7bdf6eabc305c4" ON "businesses" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_82ca19bc20713fdfa72626a5da" ON "businesses" ("slug") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."IDX_82ca19bc20713fdfa72626a5da"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cbb98c2d1e4c7bdf6eabc305c4"`);
        await queryRunner.query(`DROP TABLE "businesses"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fa75aa29a9c3f1c980cde5dbf8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_37f67f778844dcc3a0d641a617"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_68e2c25aa52093d28af9bd2011"`);
        await queryRunner.query(`DROP TABLE "campaign_recipients"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_719d46d8ea30d09f6c62978023"`);
        await queryRunner.query(`DROP TABLE "templates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_466129a2c4eab22f4bb5109de1"`);
        await queryRunner.query(`DROP TABLE "channels"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_778013f0785179c0d7ea5c279e"`);
        await queryRunner.query(`DROP TABLE "campaigns"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ad7a73cff3ca8bd780ee0a9f81"`);
        await queryRunner.query(`DROP TABLE "audiences"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d465e2a1ae2f8d311e9b09f39f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_736eb30c4220859bd55d8e7953"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_569eb5246771327e8e41fda5ce"`);
        await queryRunner.query(`DROP TABLE "contacts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3e605129623b629ddd0583740d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1a99838ee2e2e940ad98ed2e9d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d2ec6f5e4d9d16443e841ed4d8"`);
        await queryRunner.query(`DROP TABLE "conversations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1427a77e06023c250ed3794a1b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_de8978490834e2e9cb3c3fc806"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_407e4e86642d493b6d9ca7b45a"`);
        await queryRunner.query(`DROP TABLE "participants"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_177183f29f438c488b5e8510cd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e140f8ddef870ea93925f251f2"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9c89697164c20b0b9711fa03f5"`);
        await queryRunner.query(`DROP TABLE "segments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3bc55a7c3f9ed54b520bb5cfe2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1fe66d9cd8e2d40ddd8994d703"`);
        await queryRunner.query(`DROP TABLE "messages"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_963693341bd612aa01ddf3a4b6"`);
        await queryRunner.query(`DROP TABLE "organizations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6347f114eeaac28722f959f6e3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e6222f046b4fad2cab8116845e"`);
        await queryRunner.query(`DROP TABLE "workflow_executions"`);
        await queryRunner.query(`DROP TABLE "global_configs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0295721f97f1658e87f335626c"`);
        await queryRunner.query(`DROP TABLE "workflow_definitions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a69d4dba42b12bffafa4be9804"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cf6f52f2556330ac10b52a3e3f"`);
        await queryRunner.query(`DROP TABLE "workflow_triggers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e2c8160233cf87b86c30c7ebe5"`);
        await queryRunner.query(`DROP TABLE "webhook_receivers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4e83431119fa585fc7aa8b817d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ba00250f3b86a102d1653c5cda"`);
        await queryRunner.query(`DROP TABLE "workspace_members"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b8e9fe62e93d60089dfc4f175f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8e4db55375ad62da39bf574bea"`);
        await queryRunner.query(`DROP TABLE "workspaces"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_42f64325175fde14bc96827cfd"`);
        await queryRunner.query(`DROP TABLE "webhook_events"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4263dbc50a0e2a450a0244e422"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6a66686198f5bf0a4e0a339102"`);
        await queryRunner.query(`DROP TABLE "workflow_actions"`);
    }

}
